### ISSUE TITLE
Feedback from updated version (V. 0.4)

### ISSUE THREAD

**Issue by hpmaxi** [gnosis/ido-starter#12]
From Elena's feedback
- [x] Add validation to amount fields, only valid amounts should pass validation [example](https://drive.google.com/file/d/1-pISmriz0Qk6krY51va9qp6hRF3g-Wml/view)
- [x] Avoid clearing out fields if the tx is not sent. Ex. Canceled submit modal, some error inside initiateAuction
- [ ] Show a modal if the tx is successful with the auctionId + clear out the fields on the form after successful transaction
- [x] Divider between 4 and 5 field must be removed
- [x] Dates fields are narrower. 
- [x] Change in tooltipText and labels `buytAmount` to `amount to buy`, allowListManager as List Manager, etc.
- [x] Calendar is transparent, make it solid.
- [x] Invalid ERC20 for `0x4dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b` is incorrect.
- [x] No validations when dates are empty or cancelDate > closingDate. Keep 'Build transaction' disabled when date = today + time in the past. Errors could being cleared out by the build button. 
- [x] Cancel TX should not reset form.
- [x] gasPrice/gasLimit is not set automatically?
- [ ] ThirdParty errors in console.

**Comment by elena-zh** [comment]
Hi Maxi!
I think, that the next cases are already fixed:
 - Invalid ERC20 for 0x4dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b is incorrect.
 - Cancel TX should not reset form.

**Comment by hpmaxi** [comment]
@elena-zh 
Third Party errors seems related to `safe-react-app-sdk` package. I can't solve it for the moment, and about the modal with the `auctionId` there is the issue #29 . Maybe we can close this?

**Comment by elena-zh** [comment]
Hi @hpmaxi , 
yes, we can close this issue, as for unfixed cases separate issues are created. 

Thanks
