### ISSUE TITLE
[Feedback] - boolean input for allowlisting

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-starter#14]
I got the feedback that selecting the allowlist contract is too customized. 

We should simply have a boolean option:
- Do you want to use whitelisting process for your auction?

And if the boolean value is ticked, then we would ask for the signer's public key. 
The Allowlisting contract should be read from the app's code:
```
on rinkeby: 0x80b8AcA4689EC911F048c4E0976892cCDE14031E
on xdai: 0x80b8AcA4689EC911F048c4E0976892cCDE14031E
```
(PS they are the same, we used a deterministic deployment process)

**Comment by elena-zh** [comment]
Also, it would be nice to add 'validation' rules for the fields in case if a user selects 'Yes' for the option 'Do you want to use whitelisting process for your auction?'. 
Currently, a user may fill in these fields with any value he/she wants, and that will be finished with a 'failed' transaction
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f9921899-6cbe-42e5-9af8-516bda7ea432)
Hence, it would be great to validate the fields on format and do not allow to leave fields empty ( if 'Yes' is selected for the option 'Do you want to use whitelisting process for your auction?'.).
