### ISSUE TITLE
 App should also work on xDAI

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-starter#15]
Since our second customer is already on xdai, we should enable the app also on xDAI

If it is easier, we can also deploy it on a different url for different networks

**Comment by josojo** [comment]
Test with the customers will be on 30th of March

**Comment by hpmaxi** [comment]
Tried to change to `XDAI` using the correct env and had a problem with the provider given by the `safe-sdk`. I have to try again, or search for a safe app that uses `safe-react-apps-sdk` with support for XDAI.
