### ISSUE TITLE
App crashes on numbers with two decimal points

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-starter#16]
Accidently, I was putting in the number 0.00.1 and then the app crashed completely

**Comment by elena-zh** [comment]
I think the issue might be solved in #12 (action 1) - after adding validation rules (no letters, special symbols, negative amounts,  decimals with commas and more that 1 period), to 'amount' fields such issues should stop to be reproducible. 
Also, it would be great to limit a number of decimals to be allowed to enter (no more than 2, or 4, or so) as the app is crashed when I fill in more than 18 decimals)
