### ISSUE TITLE
The app is crashed when fill in 'Bidding token' field with an invalid ERC20 address

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-starter#20]
Fill in the 'Bidding token' field with an invalid ERC20 address

**AR**: the app is crashed
![image](https://user-images.githubusercontent.com/70885163/112302400-1a64a880-8cac-11eb-9c2f-ef91dcd7337b.png)

ER: 'Invalid ERC20' message is displayed

**Comment by hpmaxi** [comment]
@elena-zh This can be closed too? I think I forgot to put it on the list of issues closed by #26

**Comment by elena-zh** [comment]
Yes, please.
