### ISSUE TITLE
Biddint Token wrong address not recognized as wrong

### ISSUE THREAD

**Issue by avsavsavs** [gnosis/ido-starter#30]
While the Auctioning token field parameter does prompt a message of Invalid address whenever the address is incorrect, the bidding token field parameter does not do that but it should. 
![Screenshot 2021-03-25 at 12 55 42](https://user-images.githubusercontent.com/80408352/112486429-261fa000-8d7c-11eb-858a-7375fecb3170.png)

**Comment by elena-zh** [comment]
duplicates #19, fixed in #26
