### ISSUE TITLE
Order List empty at the end of the Auction (xDAI)

### ISSUE THREAD

**Issue by avsavsavs** [gnosis/ido-starter#37]
During the testing organized for xDAI I placed 3 different orders during the bidding time. Throughout this time, order list was showing all the orders correctly and there was no problem. Once the auction ended, the order list became blank and said I did not place any order. After claiming my auction token, as one of the orders was successful, it also said that I had not place an order. See the following image:
![image](https://user-images.githubusercontent.com/80408352/112665959-eb8d3480-8e5b-11eb-9975-30047cdc9ffc.png)

**Comment by hpmaxi** [comment]
@avsavsavs this should be in `ido-ux` issues, right?

**Comment by avsavsavs** [comment]
you are 100% right, my bad wrong repo
