### ISSUE TITLE
Update app to newest smart contracts

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-starter#8]
Use new npm package 0.4.0

This entails:
- sending over auctionEndDate , instead of auctionDuration to the contract

- sending over orderCancelationEndDate , instead of orderCancelationDuration to the contract

- sending over one more field: [`accessManagerContractData`](https://github.com/gnosis/ido-contracts/blob/main/contracts/EasyAuction.sol#L163)
Initially, for the first use cases, accessManagerContractData should be just containing an address. It should be send over as bytes like [that](https://github.com/gnosis/ido-contracts/blob/main/test/contract/AllowListManager.spec.ts#L49):

**Comment by josojo** [comment]
For comparision, here is the fronot-end update: https://github.com/gnosis/ido-ux/pull/158

**Comment by hpmaxi** [comment]
I don't have permission to view that repository (404).

**Comment by josojo** [comment]
I think its not soo important: 

this was all the relevant information from that PR

![image](https://user-images.githubusercontent.com/7348154/111331112-e1f01980-8670-11eb-8f38-de7d8020ae43.png)
